apiVersion: v1
data:
  install-config: |
    apiVersion: v1
    baseDomain: green.osp.opentlc.com
    compute:
    - hyperthreading: Enabled
      name: worker
      platform: {}
      replicas: 0
    controlPlane:
      hyperthreading: Enabled
      name: master
      platform:
        openstack:
          type: 4c16g30d
      replicas: 3
    metadata:
      creationTimestamp: null
      name: 76f2
    networking:
      clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
      machineCIDR: 192.168.47.0/24
      networkType: OpenShiftSDN
      serviceNetwork:
      - 172.30.0.0/16
    platform:
      openstack:
        cloud: 76f2-project
        computeFlavor: 4c16g30d
        externalDNS: null
        externalNetwork: external
        lbFloatingIP: 169.62.121.58
        octaviaSupport: "0"
        region: ""
        trunkSupport: "1"
    publish: External
    pullSecret: ""
    sshKey: |
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDM8j28HXpgCii+w9MnIwVnYyHiWJZvu+y+qMz+51jOLNQCTeK8y/qWb5v7r/jKX6braSuT5l6U+zLNnzLcHlKtHBIxNgzScSTo164qHvg8ZCu6ti7kpl3MXuokcG13xELni9rcgrGWrW4XaPRiCditqEInhSM5GXV39FdfumpQAqfbmoEWZkIkdJOheeDN60ZvXyytF2zoNLaHGwuj8LoNpiFb8LMANBewcibVUM6OgjNBC2j2mCwkjtfL4gzePEb2+Y72Cm01YF2+W63B2CVF/7B0QbYBR22OIPCkQy3TmrjQ4OUwTZhap2WvSpklxP/5ArtPqgWyt+/0TS+hXOF9 opentlc-mgr@admin.na.shared.opentlc.com
kind: ConfigMap
metadata:
  name: cluster-config-v1
  namespace: kube-system
