apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-storage 
spec:
  capacity:
    storage: 100Gi 
  accessModes:
  - ReadWriteMany 
  nfs: 
    path: /ocp-registry
    server: utilityvm.example.com
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs